"""Création des tabledfsds Produit et Vente

Revision ID: 54622a22b8fc
Revises: 
Create Date: 2025-08-11 11:48:44.795952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54622a22b8fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('benefice', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produit', schema=None) as batch_op:
        batch_op.drop_column('benefice')

    # ### end Alembic commands ###
