"""Création des tables Produit, Vente, ProduitStock

Revision ID: 918ea35740fa
Revises: bc3bd3e97e60
Create Date: 2025-08-14 13:53:27.508379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918ea35740fa'
down_revision = 'bc3bd3e97e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produit_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idproduit', sa.Integer(), nullable=False),
    sa.Column('qte', sa.Integer(), nullable=False),
    sa.Column('type_mouvement', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idproduit'], ['produit.idproduit'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produit_stock')
    # ### end Alembic commands ###
