"""Création des tabledfsds Produit et Ventde

Revision ID: bc3bd3e97e60
Revises: 54622a22b8fc
Create Date: 2025-08-11 12:10:44.964978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3bd3e97e60'
down_revision = '54622a22b8fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produit',
    sa.Column('idproduit', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('qte', sa.Integer(), nullable=False),
    sa.Column('prix', sa.Double(), nullable=False),
    sa.Column('benefice', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('idproduit')
    )
    op.create_table('vente',
    sa.Column('idvente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idproduit', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('qte', sa.Integer(), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['idproduit'], ['produit.idproduit'], ),
    sa.PrimaryKeyConstraint('idvente')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vente')
    op.drop_table('produit')
    # ### end Alembic commands ###
