"""Création des tables Produit, Vente, ProduitStock

Revision ID: e5de78915d6e
Revises: 918ea35740fa
Create Date: 2025-08-14 14:17:50.750569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5de78915d6e'
down_revision = '918ea35740fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vente', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('vente_idproduit_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'produit', ['idproduit'], ['idproduit'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('vente_idproduit_fkey'), 'produit', ['idproduit'], ['idproduit'])

    # ### end Alembic commands ###
